In [1]:
import numpy as np

In [3]:
a_list = [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista

idealna_lista = ["a","b","c"]
k_krotka = (1,2,3,4,5, [1,2,3], "temat") #tuple
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [16]:
%%timeit
*odpakowana, lista2, string3 = k_krotka #odpakowywanie krotki, unpacking

#print(lista2)

raz, *reszta = lista2

reszta

619 ns ± 27.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
b_list + b_list
np.array(b_list) + np.array(b_list)
2 * n_array

array([ 2,  4,  6,  8, 10])

In [14]:
%%timeit
n_array.dot(n_array)


1.52 µs ± 30.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [12]:
a_list[3]

NameError: name 'k_list' is not defined

In [22]:
print(a_list)
a_list.append(100)
print(a_list)

a_list.extend([1,2,3,4,5,6])

a_list

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100, 100, 100, 100, 100, 1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100, 100, 100, 100, 100, 1, 2, 3, 4, 5, 6, 100]


[1,
 2,
 3,
 4,
 5,
 [1, 2, 3],
 'temat',
 100,
 100,
 100,
 100,
 100,
 1,
 2,
 3,
 4,
 5,
 6,
 100,
 1,
 2,
 3,
 4,
 5,
 6]

In [13]:
k_krotka[4]

5

In [29]:
#k_krotka.append(100)
k_krotka
#k_krotka.__hash__()
(1,2,3).__hash__()

529344067295497451

In [8]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [9]:
n_array = np.array(a_list) # wektor numpy

In [10]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat'], dtype=object)

In [31]:
#### Nowosci

studenci_slownik = {123: 123,
                    "Igor":3,
                    "Frankek":5,
                    "Zosia":22,
                    "Julia":[2,21],
                    (1,2):"Krotka"}
print(studenci_slownik["Julia"])

studenci_slownik["Igor"] = 5

studenci_slownik["Genowefa"] = 6

[2, 21]


In [32]:
%%timeit
"Igor" in studenci_slownik

65.2 ns ± 2.62 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [33]:
lista_studentow = ["Anna","Franek", "Zosia", "Julia","Igor"]

In [34]:
%%timeit
lista_studentow

42.1 ns ± 1.65 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [18]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [21]:
studenci_slownik["Zosia"]

22

In [35]:
for klucze in studenci_slownik:
    print(klucze)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
Genowefa
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)
Genowefa


In [23]:
for elementy in studenci_slownik.items():
    print(elementy)

('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])


In [24]:
for elementy in studenci_slownik.values():
    print(elementy)

3
5
22
[2, 21]


In [30]:
studenci_slownik["Cuthulu"]= -1000000

In [31]:
studenci_slownik

{'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], 'Cuthulu': -1000000}

In [29]:
jakas_zmienna = 100

In [30]:
jakas_lista = []
for liczba in range(100):
    if liczba%4 == 0: # czy podzielne przez 4
        jakas_lista.append(liczba**2)
        
print(jakas_lista)
        

100
[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [28]:
automatyczna_lista = [liczba**2 for liczba in range(100) if liczba%4 == 0]
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [34]:
studenci = studenci_slownik.keys()
print(studenci)
next(enumerate(studenci))

dict_keys([123, 'Igor', 'Frankek', 'Zosia', 'Julia', (1, 2), 'Genowefa'])


(0, 123)

In [35]:
tworzony_przez_krotki = dict([("klucz","wartosc"),["inny_klucz","inna_wartosc"]])
print(tworzony_przez_krotki)

{'klucz': 'wartosc', 'inny_klucz': 'inna_wartosc'}


In [36]:
studenci = studenci_slownik.keys()
automatyczny_slownik = dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 'Igor', 1: 'Frankek', 2: 'Zosia', 3: 'Julia', 4: 'Cuthulu'}


In [36]:
##### zbiory / set

a = {1,2,3,"Franek"}
b = {2,3,4,"Franek"}


In [37]:
"Franek" in a

True

In [23]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [40]:
lista2.pop()

3

In [43]:
lista2.pop()

IndexError: pop from empty list

In [24]:
a.add("Franek")
print(a)

{1, 2, 3, 'Franek'}


In [25]:
1 in a
"Igor" in studenci_slownik

True

### Własne typy

In [107]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg = ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [63]:
class Pusta():
    pass

a = Pusta()
a.__dict__

{}

In [71]:
class PrzykladowaKlasa():
    """ta klasa nic madrego nie robi"""
    def __init__(self, argument):
        print(f"Podales argument {argument}!!!")
        
        self.wiek = argument
    
    def printuj_wiek(self):
        print(self)
    
    @property
    def dwa_razy_wiek(self):
        return self.wiek * 2
    
    def __mul__(self, drugi_obiekt):
        return self.wiek * drugi_obiekt.wiek
    
    def __repr__(self):
        wyswietl = f"Wiek usera to {self.wiek}"
        return wyswietl 

In [74]:
nowy_obiekt = PrzykladowaKlasa(5)
nowy_obiekt2 = PrzykladowaKlasa(6)

nowy_obiekt * nowy_obiekt2
nowy_obiekt.wiek = 100
nowy_obiekt.dwa_razy_wiek

Podales argument 5!!!
Podales argument 6!!!


200

In [57]:
print(nowy_obiekt)

Wiek usera to 5


In [43]:
nowy_obiekt.wiek = 10

In [44]:
nowy_obiekt.wiek

10

In [65]:
nowy_obiekt * 2

10

In [56]:
nowy_obiekt.printuj_wiek

masz 5 lat


In [46]:
nowy_obiekt.imie = "Franek"

In [45]:
nowy_obiekt.wiek = 3
nowy_obiekt.printuj_wiek()

Wiek usera to 3


In [50]:
nowy_obiekt.zenon = print

In [51]:
nowy_obiekt.zenon("hello")

hello


In [66]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [80]:
def nowa_funkcja():
    pass

numer = -1
numer.__abs__()
abs(numer)

1

In [75]:
" , ".join(["Igor","Andrzej","Helga"]).split(",")

['Igor ', ' Andrzej ', ' Helga']

In [67]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [68]:
pio_zajecia.ile_zajec

4

In [69]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [33]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [34]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [35]:
pio_zajecia.ile_mispow()

4

In [95]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [85]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [105]:
print(pio_zajecia.ile_zajec)

5


In [108]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [109]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [112]:
posortowane_po_zajeciach=sorted(lista_zajec, key = lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key = lambda zajecie: zajecie.ile_mispow())

In [113]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [114]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


##### challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
 

In [87]:
" ".join(["a","b c","c"]).split(" ")
[1,2,3][10]

IndexError: list index out of range

In [99]:
lista = [1,2,3,4]


prostrza_wersja_map = [2*element for element in lista if element<4]
prostrza_wersja_map = list(map(lambda element: 2*element, lista))
print(prostrza_wersja_map)

[2, 4, 6, 8]


In [92]:
fufu = [1,
        2]

slownik = {"aa" : "bb",
                               "sdasdsd":"ssddssd"
          }

dlugi_string ="""dskdsmksdfklmsd
dfsdfsdfsdfs
dfssdfsdfsdfsdf
sdfsdfsdf"""


In [ ]:
# ma na takie rzeczy być w stanie odpowiedzieć

numer_lodz = NumerTelefonu("426877868")
>>> "prawidlowy numer"

numer_lodz.wojewodztwo 
>>> "Lodz"

print(numer_lodz)
>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"

In [1]:
### uPodpowiedzi

lista_numerkow = list("1234")


def jaki_kierunkowy(numer_str):
    dwie_cyfry = numer_str[0:2]
    if dwie_cyfry in numer2wojewodztwo:
        return numer2wojewodztwo[dwie_cyfry]
    else:
        return "Komorkowy"



#for cyfra in lista_numerkow:
#    print(po_polsku_cyfry[cyfra])

    
" ".join(po_polsku_cyfry[cyfra] for cyfra in lista_numerkow)    


class NumerTelefonu():
    numer2wojewodztwo = {"89": "Olsztyn"}
    
    po_polsku_cyfry = {"1":"jeden","2":"dwa","3":"trzy", 
                   "4":"cztery", "6":"szesc","7":"siedem","8":"osiem"}
    def __init__(self, numer_tel):
        if(len(numer_tel) != 9): #sprawdzam czy odpowiednia dlugosc numeru 
            print("zly numer")
            return 
        self.numer_tel = str(numer_tel)
    @property
    def wojewodztwo(self):
        dwie_cyfry = self.numer_tel[0:2]
        if dwie_cyfry in self.numer2wojewodztwo:
            return self.numer2wojewodztwo[dwie_cyfry]
        else:
            return "Komorkowy"
        
        
    def __repr__(self):
        lista_numerkow = list(self.numer_tel)
        
        return " ".join(self.po_polsku_cyfry[cyfra] for cyfra in lista_numerkow)    

    
czyjs_numer = NumerTelefonu(426877868)
print(czyjs_numer)
#jaki_kierunkowy("8934")

TypeError: object of type 'int' has no len()

In [3]:
%debug

> <ipython-input-1-952a0e12d666>(28)__init__()
     26 
     27     def __init__(self, numer_tel):
---> 28         if(len(numer_tel) != 9): #sprawdzam czy odpowiednia dlugosc numeru
     29             print("zly numer")
     30             return

ipdb> numer_tel
426877868
ipdb> len(numer_tel)
*** TypeError: object of type 'int' has no len()
ipdb> len(str(numer_tel))
9
--KeyboardInterrupt--
ipdb> exit


In [ ]:
czyjs_numerumer

In [85]:
class NowyBlad(Exception):
    pass

try:
    2+2
    raise NowyBlad
except TypeError:
    print("no co ty, nie da się")
except KeyError:
    print("ni mo")
except:
    print("inny blad")

inny blad
